### ISSUE TITLE
"Nullable object must have a value" in BlazorStrap.CodeBSNavItem.MouseDown() in BlazorStrap 1.0.0-preview7-02

### ISSUE THREAD

**Issue by noahc3** [chanan/BlazorStrap#146]
When clicking on a BSNavItem in 1.0.0-preview7-02, the component renderer will fail with `Error: System.InvalidOperationException: Nullable object must have a value.`. This occurs in both client-side and server-side Blazor, and does not occur in BlazorStrap 1.0.0-preview7-01. Seems to happen with any of the BSNav examples on the docs.

Exception output for a server-side Blazor project:

```
warn: Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer[100]
      Unhandled exception rendering component: Nullable object must have a value.
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at BlazorStrap.CodeBSNavItem.MouseDown()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.DispatchEventAsync(Int32 eventHandlerId, EventFieldInfo fieldInfo, UIEventArgs eventArgs)
```

and in a client-side Blazor project:

```
WASM: ﻿Unhandled exception rendering component:
WASM: System.InvalidOperationException: Nullable object must have a value.
WASM:   at System.Nullable`1[T].get_Value () <0x1b96db0 + 0x0000c> in <cc1bc40928c04a60b5cfb5ca86332855>:0 
WASM:   at BlazorStrap.CodeBSNavItem.MouseDown () <0x2288920 + 0x0009e> in <9ab6005ec4064b66bd44daaaacb3f289>:0 
WASM:   at (wrapper delegate-invoke) <Module>.invoke_void()
WASM:   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T] (System.MulticastDelegate delegate, T arg) <0x2288760 + 0x00072> in <b9c0a2e1f675400685e6d6841f63a5eb>:0 
WASM:   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync (System.Object arg) <0x2288630 + 0x0000c> in <b9c0a2e1f675400685e6d6841f63a5eb>:0 
WASM:   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync (Microsoft.AspNetCore.Components.EventCallbackWorkItem callback, System.Object arg) <0x2288598 + 0x0000a> in <b9c0a2e1f675400685e6d6841f63a5eb>:0 
WASM:   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync (System.Object arg) <0x227ded0 + 0x00046> in <b9c0a2e1f675400685e6d6841f63a5eb>:0 
WASM:   at Microsoft.AspNetCore.Components.Rendering.Renderer.DispatchEventAsync (System.Int32 eventHandlerId, Microsoft.AspNetCore.Components.Rendering.EventFieldInfo fieldInfo, Microsoft.AspNetCore.Components.UIEventArgs eventArgs) <0x227d800 + 0x00082> in <b9c0a2e1f675400685e6d6841f63a5eb>:0 
Uncaught (in promise) Error: System.NullReferenceException: Object reference not set to an instance of an object.
  at Microsoft.AspNetCore.Components.Rendering.Renderer.GetErrorHandledTask (:51436/System.Threading.Tasks.Task taskToHandle) <0x207b3b0 + 0x00114> in <b9c0a2e1f675400685e6d6841f63a5eb>:0 
    at endInvokeDotNetFromJS (blazor.webassembly.js:1)
    at Object.invokeJSFromDotNet (blazor.webassembly.js:1)
    at _mono_wasm_invoke_js_marshalled (mono.js:1)
    at :51436/wasm-function[6300]:382
    at :51436/wasm-function[1947]:126
    at :51436/wasm-function[597]:5081
    at :51436/wasm-function[597]:6805
    at :51436/wasm-function[597]:6094
    at :51436/wasm-function[597]:6805
    at :51436/wasm-function[597]:4824
```

**Comment by chanan** [comment]
Thanks for the report. We will check it out ASAP

**Comment by jbomhold3** [comment]
Fixed in next release
