### ISSUE TITLE
BSTabGroup not working in ServerPrerendered?

### ISSUE THREAD

**Issue by timbze** [chanan/BlazorStrap#270]
Looking at #191, it almost seems to say Tabs will not work when settings are on ServerPrerendered? Is that correct? I've been using some different components from BlazorStrap but couldn't figure out why Tabs were not working properly yet (i.e. not showing any data in BSTabContent)

Are there any plans to make it working?

**Comment by jbomhold3** [comment]
No, they will work prerendered they will just not take part in the prerendering. Tabs are stateful and need the circuit or client to be live to function properly. Nothing should render until its ready. That being said the fix is rather old it might have broken. Will look into it.

**Comment by timbze** [comment]
I'm trying it again now and it works. Either I missed something when I tried or something changed, using preview version 02 now.

**Comment by timbze** [comment]
There is, however, this error on reloading page with tabs. Seems to still work though.

Server mode, navigating from other page to page with tabs, no error.

When on page with tabs, press refresh page and I get the following error:
```
2020-05-01 15:13:34.9975|111|ERROR|Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost+Log.CircuitUnhandledException|Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost|Unhandled exception in circuit 'WMIjceGkRiiEs-_HXESspiMsIfeoPcK0Pq_urHfLjC8'. System.AggregateException: Exceptions were encountered while disposing components. (Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.) (Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.) (Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.) (Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.)
 ---> System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback`1.InvokeAsync(TValue arg)
   at BlazorStrap.BSTabGroupBase.<set_Selected>b__27_0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Func`1 workItem)
   at BlazorStrap.BSTabGroupBase.set_Selected(BSTabBase value)
   at BlazorStrap.BSTabBase.Dispose(Boolean disposing)
   at BlazorStrap.BSTabBase.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
Object name: 'Renderer'.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback`1.InvokeAsync(TValue arg)
   at BlazorStrap.BSTabGroupBase.<set_Selected>b__27_0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Func`1 workItem)
   at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Func`1 workItem)
   at BlazorStrap.BSTabGroupBase.set_Selected(BSTabBase value)
   at BlazorStrap.BSTabBase.Dispose(Boolean disposing)
   at BlazorStrap.BSTabBase.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)<---
```

Using this code
```razor
<BSTabGroup>
    <BSTabList>
        <BSTab Id="@Tabs.Main">
            <BSTabLabel>Main</BSTabLabel>
            <BSTabContent>
                Text main
            </BSTabContent>
        </BSTab>
        <BSTab Id="@Tabs.Second">
            <BSTabLabel>Second</BSTabLabel>
            <BSTabContent>
                Other text
            </BSTabContent>
        </BSTab>
    </BSTabList>
    <BSTabSelectedContent />
</BSTabGroup>

@code{
    private class Tabs
    {
        public const string Main = "tabMain";
        public const string Second = "tabSecond";
    }
}
```
