### ISSUE TITLE
Bootstrap API not working with Razor App Template on Visual Studio Version 16.7.0 Preview 2.0

### ISSUE THREAD

**Issue by MasterSkriptor** [chanan/BlazorStrap#347]
Repo

1.  Update to Visual Studio Version 16.7.0 Preview 2.0
2. Create new Blazor App (Server or WebAssembly)
3. Install BlazorStrap using instructions on BlazorStrap.io
4. Follow instructions for Add the CSS to your project on index page of BlazorStrap.io
5. Run the app

##Error Details from WASM Template:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'blazorStrap' in 'window'.
      Error: Could not find 'blazorStrap' in 'window'.
          at https://localhost:44358/_framework/blazor.webassembly.js:1:9198
          at Array.forEach (<anonymous>)
          at p (https://localhost:44358/_framework/blazor.webassembly.js:1:9158)
          at https://localhost:44358/_framework/blazor.webassembly.js:1:9868
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44358/_framework/blazor.webassembly.js:1:9841)
          at _mono_wasm_invoke_js_marshalled (https://localhost:44358/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171346)
          at do_icall (<anonymous>:wasm-function[6049]:0x111976)
          at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x52c3e)
          at interp_exec_method (<anonymous>:wasm-function[1120]:0x25a03)
Microsoft.JSInterop.JSException: Could not find 'blazorStrap' in 'window'.
Error: Could not find 'blazorStrap' in 'window'.
    at https://localhost:44358/_framework/blazor.webassembly.js:1:9198
    at Array.forEach (<anonymous>)
    at p (https://localhost:44358/_framework/blazor.webassembly.js:1:9158)
    at https://localhost:44358/_framework/blazor.webassembly.js:1:9868
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44358/_framework/blazor.webassembly.js:1:9841)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44358/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171346)
    at do_icall (<anonymous>:wasm-function[6049]:0x111976)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x52c3e)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x25a03)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2dd5370 + 0x00034> in <filename unknown>:0 
  at BlazorStrap.Util.BootstrapCss.SetBootstrapCss (System.String theme, System.String version) <0x2ce32e0 + 0x00118> in <filename unknown>:0 
  at BlazorApp1.Shared.MainLayout.OnInitializedAsync () [0x0002a] in C:\Code\BlazorApp1\BlazorApp1\Shared\MainLayout.razor:22 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2bd09f0 + 0x0013a> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2cf39d0 + 0x000b6> in <filename unknown>:0 

##Error on ServerSide
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendererd. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at BlazorStrap.Util.BootstrapCss.SetBootstrapCss(String theme, String version)
   at BlazorApp2.Shared.MainLayout.OnInitializedAsync() in C:\Code\BlazorApp2\BlazorApp2\Shared\MainLayout.razor:line 21
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasks(Task task)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
   at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at BlazorApp2.Pages.Pages__Host.<ExecuteAsync>b__14_1() in C:\Code\BlazorApp2\BlazorApp2\Pages\_Host.cshtml:line 19
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at BlazorApp2.Pages.Pages__Host.ExecuteAsync() in C:\Code\BlazorApp2\BlazorApp2\Pages\_Host.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

If you change <component type="typeof(App)" render-mode="ServerRendered" /> to <component type="typeof(App)" render-mode="Server" /> in _Host.cshtml it works fine on the server.

 I discovered this while working on #346 

##Helpful info
The WebAssembly app is using Version 3.2.0-preview5.20216.13 of Microsoft.AspNetCore.Components.WebAssembly

**Comment by jbomhold3** [comment]
Got to add the JS file per the install steps on GitHub readme 
"Add <script src="_content/BlazorStrap/blazorStrap.js"></script> inside the <head> element of your Pages/_Host.cshtml. In startup add Services.AddBootstrapCss();"

**Comment by chucker** [comment]
Just to be clear, your WASM index.html does reference the JS?

**Comment by MasterSkriptor** [comment]
Yes, I didnt add the JScript files on the client side, which fixed that issue. I was too focused on following the documentation to catch that.

What is the deal with this not working? Is that expected? 
<component type="typeof(App)" render-mode="ServerPrerendered" />

If you change it to:
<component type="typeof(App)" render-mode="Server" />
it works fine. Is this by design?

I can see that we need to do some work on the documentation for the installation. Everytime I have done it before I ignored the setup instructions.... lol. I also havent set up a fresh installation of BlazorStrap in quite a while, several versions back actually. In fact the main website I am working on that is blazor has BlazorStrap 1.3.1 installed, and I am pretty sure I updated it to that... lol.

**Comment by MasterSkriptor** [comment]
You can mark this a duplicate of #346 if you want.

**Comment by jbomhold3** [comment]
I would add that part to the code review back in the dark ages of beta pre-rendered work differently and changed every release. Kinda need to update fully. Some components just work with prerendering on others need active state management to work correctly. Most of this can be addressed now. I think leading up to 5.0 we are going to end up having to rewrite a few of the components completely. Not tossing out the code just changing how they work at their core. bsmodel would be a good example. would like to completely remove the isopen and use the ref show hide method. It's why I shifted the code on docs to stop using any isopen directly. Will see of chanan is in agreement with me if he is we can flag that for example as obsolete. Part of the reason I wanted to do the review to identify now things we would like to improve or change so we can get it flagged early so its not a surprise braking change for people

**Comment by chucker** [comment]
>What is the deal with this not working? Is that expected?
<component type="typeof(App)" render-mode="ServerPrerendered" />

Not that experienced in Blazor Server, but ServerPrerendered has no JavaScript. If non-JS bits of BlazorStrap don't properly work during prerendering, that seems like a bug we should investigate. Can you expand on "not working"?

**Comment by MasterSkriptor** [comment]
The problems in this issue have been resolved by #348 and #349
