### ISSUE TITLE
Focused BSInput with OnValidSubmit+NavigationManager.NavigateTo

### ISSUE THREAD

**Issue by jespersh** [chanan/BlazorStrap#354]
BlazorStrap 1.3.2

When an BSInput field has focus and I hit Enter, as `NavigationManager.NavigateTo` is executed, then an exception is hit (see console error below).
It seems somewhat related to https://github.com/dotnet/aspnetcore/issues/21241 where the OnBlur in BSInput is tried but errors: https://github.com/chanan/BlazorStrap/blob/43189e63f4ba20e480f488699667e4f746a4fb07/src/BlazorStrap/Components/Forms/BSInput.cs#L247

This rather simple form
```
    <BSForm @ref="BsFormRef" Model="@formModel" ValidateOnInit="true" OnValidSubmit="HandleValidSubmit" OnInvalidSubmit="HandleInvalidSubmit">
        <DataAnnotationsValidator />
        <BSRow>
            <BSFormGroup Class="col-md-12">
                <BSLabel For="name">Navn</BSLabel>
                <BSInput InputType="InputType.Text" Id="name" @bind-Value="@formModel.Name" ValidateOnChange="true" />
                <BSFormFeedback For="@(() => formModel.Name)" ValidMessage="Ledig" />
            </BSFormGroup>
        </BSRow>

        <BSButton Color="Color.Primary" ButtonType="ButtonType.Submit">Gem</BSButton>
    </BSForm>
```

With this method for OnValidSubmit
```
    private async void HandleValidSubmit()
    {
        Console.WriteLine("OnValidSubmit");
        if (await Client.SaveService(formModel))
        {
            NavigationManager.NavigateTo("/services");
        }
    }
```

The lengthy error:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unknown edit type: 0
      Error: Unknown edit type: 0
          at e.applyEdits (https://localhost:5001/_framework/blazor.webassembly.js:1:15076)
          at e.updateComponent (https://localhost:5001/_framework/blazor.webassembly.js:1:12948)
          at Object.t.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:1704)
          at Object.window.Blazor._internal.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:34848)
          at _mono_wasm_invoke_js_unmarshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:172099)
          at wasm_invoke_iiiiii (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3160]:0x9b33d)
          at icall_trampoline_dispatch (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[5777]:0xfe711)
          at mono_wasm_interp_to_native_trampoline (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[4607]:0xca81d)
          at ves_pinvoke_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3209]:0x9cd40)
          at interp_exec_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2598d)
Microsoft.JSInterop.JSException: Unknown edit type: 0
Error: Unknown edit type: 0
    at e.applyEdits (https://localhost:5001/_framework/blazor.webassembly.js:1:15076)
    at e.updateComponent (https://localhost:5001/_framework/blazor.webassembly.js:1:12948)
    at Object.t.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:1704)
    at Object.window.Blazor._internal.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:34848)
    at _mono_wasm_invoke_js_unmarshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:172099)
    at wasm_invoke_iiiiii (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3160]:0x9b33d)
    at icall_trampoline_dispatch (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[5777]:0xfe711)
    at mono_wasm_interp_to_native_trampoline (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[4607]:0xca81d)
    at ves_pinvoke_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3209]:0x9cd40)
    at interp_exec_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2598d)
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,T2,TResult] (System.String identifier, T0 arg0, T1 arg1, T2 arg2) <0x30763d0 + 0x00046> in <filename unknown>:0 
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,TResult] (System.String identifier, T0 arg0, T1 arg1) <0x30762f0 + 0x00014> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync (Microsoft.AspNetCore.Components.RenderTree.RenderBatch& batch) <0x30761f8 + 0x0001e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x2e3b5e0 + 0x000f2> in <filename unknown>:0 
f.printErr @ blazor.webassembly.js:1
f.preRun.push.window.Blazor._internal.dotNetCriticalError @ blazor.webassembly.js:1
_mono_wasm_invoke_js_unmarshalled @ dotnet.3.2.0.js:1
do_icall @ dotnet.wasm:1
do_icall_wrapper @ dotnet.wasm:1
interp_exec_method @ dotnet.wasm:1
interp_runtime_invoke @ dotnet.wasm:1
mono_jit_runtime_invoke @ dotnet.wasm:1
do_runtime_invoke @ dotnet.wasm:1
mono_runtime_invoke_checked @ dotnet.wasm:1
mono_runtime_try_invoke_array @ dotnet.wasm:1
ves_icall_InternalInvoke @ dotnet.wasm:1
ves_icall_InternalInvoke_raw @ dotnet.wasm:1
do_icall @ dotnet.wasm:1
do_icall_wrapper @ dotnet.wasm:1
interp_exec_method @ dotnet.wasm:1
interp_runtime_invoke @ dotnet.wasm:1
mono_jit_runtime_invoke @ dotnet.wasm:1
do_runtime_invoke @ dotnet.wasm:1
mono_runtime_try_invoke @ dotnet.wasm:1
mono_runtime_invoke @ dotnet.wasm:1
mono_wasm_invoke_method @ dotnet.wasm:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
call_method @ dotnet.3.2.0.js:1
(anonymous) @ dotnet.3.2.0.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
s @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
d @ blazor.webassembly.js:1
f @ blazor.webassembly.js:1
l @ blazor.webassembly.js:1
invokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.3.2.0.js:1
do_icall @ dotnet.wasm:1
do_icall_wrapper @ dotnet.wasm:1
interp_exec_method @ dotnet.wasm:1
interp_runtime_invoke @ dotnet.wasm:1
mono_jit_runtime_invoke @ dotnet.wasm:1
do_runtime_invoke @ dotnet.wasm:1
mono_runtime_try_invoke @ dotnet.wasm:1
try_invoke_perform_wait_callback @ dotnet.wasm:1
worker_callback @ dotnet.wasm:1
fire_tp_callback @ dotnet.wasm:1
mono_background_exec @ dotnet.wasm:1
Module._mono_background_exec @ dotnet.3.2.0.js:1
pump_message @ dotnet.3.2.0.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.3.2.0.js:1
mono_threads_schedule_background_job @ dotnet.wasm:1
ves_icall_System_Threading_ThreadPool_RequestWorkerThread @ dotnet.wasm:1
ves_icall_System_Threading_ThreadPool_RequestWorkerThread_raw @ dotnet.wasm:1
do_icall @ dotnet.wasm:1
do_icall_wrapper @ dotnet.wasm:1
interp_exec_method @ dotnet.wasm:1
interp_runtime_invoke @ dotnet.wasm:1
mono_jit_runtime_invoke @ dotnet.wasm:1
do_runtime_invoke @ dotnet.wasm:1
mono_runtime_invoke_checked @ dotnet.wasm:1
mono_runtime_try_invoke_array @ dotnet.wasm:1
ves_icall_InternalInvoke @ dotnet.wasm:1
ves_icall_InternalInvoke_raw @ dotnet.wasm:1
do_icall @ dotnet.wasm:1
do_icall_wrapper @ dotnet.wasm:1
interp_exec_method @ dotnet.wasm:1
interp_runtime_invoke @ dotnet.wasm:1
mono_jit_runtime_invoke @ dotnet.wasm:1
do_runtime_invoke @ dotnet.wasm:1
mono_runtime_try_invoke @ dotnet.wasm:1
mono_runtime_invoke @ dotnet.wasm:1
mono_wasm_invoke_method @ dotnet.wasm:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0.js:1
call_method @ dotnet.3.2.0.js:1
invoke_delegate @ dotnet.3.2.0.js:1
(anonymous) @ dotnet.3.2.0.js:1
Show 27 more frames from Library code
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No element is currently associated with component 61
      Error: No element is currently associated with component 61
          at e.updateComponent (https://localhost:5001/_framework/blazor.webassembly.js:1:12412)
          at Object.t.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:1704)
          at Object.window.Blazor._internal.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:34848)
          at _mono_wasm_invoke_js_unmarshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:172099)
          at wasm_invoke_iiiiii (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3160]:0x9b33d)
          at icall_trampoline_dispatch (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[5777]:0xfe711)
          at mono_wasm_interp_to_native_trampoline (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[4607]:0xca81d)
          at ves_pinvoke_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3209]:0x9cd40)
          at interp_exec_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2598d)
          at interp_runtime_invoke (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[5655]:0xf7391)
Microsoft.JSInterop.JSException: No element is currently associated with component 61
Error: No element is currently associated with component 61
    at e.updateComponent (https://localhost:5001/_framework/blazor.webassembly.js:1:12412)
    at Object.t.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:1704)
    at Object.window.Blazor._internal.renderBatch (https://localhost:5001/_framework/blazor.webassembly.js:1:34848)
    at _mono_wasm_invoke_js_unmarshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:172099)
    at wasm_invoke_iiiiii (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3160]:0x9b33d)
    at icall_trampoline_dispatch (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[5777]:0xfe711)
    at mono_wasm_interp_to_native_trampoline (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[4607]:0xca81d)
    at ves_pinvoke_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[3209]:0x9cd40)
    at interp_exec_method (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2598d)
    at interp_runtime_invoke (https://localhost:5001/_framework/wasm/dotnet.wasm:wasm-function[5655]:0xf7391)
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,T2,TResult] (System.String identifier, T0 arg0, T1 arg1, T2 arg2) <0x30763d0 + 0x00046> in <filename unknown>:0 
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,TResult] (System.String identifier, T0 arg0, T1 arg1) <0x30762f0 + 0x00014> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync (Microsoft.AspNetCore.Components.RenderTree.RenderBatch& batch) <0x30761f8 + 0x0001e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x2e3b5e0 + 0x000f2> in <filename unknown>:0 
```

**Comment by jbomhold3** [comment]
Think this is a rendering issue vs blazorstrap issue. Your changing on navigating in a thread. Do me a favor and try await InvokeAsync(() =>  NavigationManager.NavigateTo("/services")); That way it invokes on the main thread.

**Comment by jespersh** [comment]
Using `InvokeAsync(() => NavigationManager.NavigateTo("/services"));` worked for me, thanks. Forgot to post back here.
