### ISSUE TITLE
BSCarousel Exception, on MouseLeave

### ISSUE THREAD

**Issue by CliveBennett** [chanan/BlazorStrap#433]
Hi, 
After Login I redirect to a page that contains a Carousel. The page loads OK, as does the Carousel
However if I mouse over the Carousel, I get this exception when the Mouse leaves the control

If I ignore the message, it doesnt happen a 2nd time

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1[[BlazorStrap.BSCarouselItem, BlazorStrap, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
   at BlazorStrap.BSCarousel.ResetTimer()
   at BlazorStrap.BSCarousel.OnMouseLeave()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
   
   My page is pretty simple
   
   
   <div style="max-width: 70%;">
    <BSCarousel Interval="3000" NumberOfItems="imageList.Length" Fade="true" Wrap="true">
        <div class="carousel-inner">
            @foreach (string image in imageList)
            {
                <BSCarouselItem Src="@($"api/workbench/image/{image}")" />
            }
        </div>
    </BSCarousel>
</div>

@code {
    [CascadingParameter]
    public CurrentUser CurrentUser { get; set; }

    string[] imageList = new string[]
    {
        "dashboard1.png",
        "dashboard2.png",
        "dashboard3.png",
            };
}

**Comment by CliveBennett** [comment]
OK , found the issue. I had just tried added CascadingAuthenticationState  to my App.Razor
Which, had caused my entire page to be duplicated if I scrolled down,  So im guessing the Carousel became confused with 2 instances or something like that.

I removed the CascadingAuthenticationState and CascadingValue elements and everything working again. 


<UserSettingsComponent>
    <CascadingAuthenticationState>
        <Router AppAssembly="@typeof(Program).Assembly">

            <Found Context="routeData">
                <CascadingValue Value="@routeData">
                    <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
                </CascadingValue>
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                    <NotAuthorized>
                        <p>You do not have permission to view this page</p>
                    </NotAuthorized>
                </AuthorizeRouteView>
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
        </CascadingAuthenticationState>
</UserSettingsComponent>

**Comment by jbomhold3** [comment]
This seams to be related to #409
