### ISSUE TITLE
BSModal Object Reference if you dont have a Footer

### ISSUE THREAD

**Issue by CliveBennett** [chanan/BlazorStrap#506]
Have recently updated to BS5, and a page will crash if you dont have a footer in a BSModal

```
//Object Reference
<BSModal>
    <Header></Header>
    <Content>
    stuff
    </Content>
</BSModal>

//WORKS
<BSModal>
    <Header></Header>
    <Content>
    stuff
    </Content>
    <Footer></Footer>
</BSModal>
```

System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorStrap.BSModal.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

**Comment by jbomhold3** [comment]
#496 sound have fixed this make sure you using the least preview version. Our previews are stable new features are just in the design phase so are subject to change nothing more.

**Comment by CliveBennett** [comment]
Thanks,  will install preview version, cheers

**Comment by jbomhold3** [comment]
Added Support in [5.0.105](https://www.nuget.org/packages/BlazorStrap/5.0.105)
